# Generated by Django 3.2.14 on 2022-07-19 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amd_recorded', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(max_length=30)),
                ('frequency', models.TextField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('created', models.DateTimeField()),
                ('recurring', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('amt_done', models.CharField(max_length=20)),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.goal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='current_goals',
            name='goal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.goal'),
        ),
        migrations.AddField(
            model_name='current_goals',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
