# Generated by Django 3.2.14 on 2022-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220719_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='frequency',
            field=models.CharField(max_length=20),
        ),
    ]
