# Generated by Django 3.2.14 on 2022-07-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_goal_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='activity',
        ),
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(default='untitled', max_length=20),
            preserve_default=False,
        ),
    ]
